title: <p align="center"> Kanika Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">

  <a href="https://github.com/kanika-github">GitHub</a>
  
  <br>   
  I'm working on Data Science and Data Analytics.
  <br>
  </p>



google_analytics:
theme: jekyll-theme-minimal
